// Generated by view binder compiler. Do not edit!
package app.grapheneos.camera.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import androidx.viewpager2.widget.ViewPager2;
import app.grapheneos.camera.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class GalleryBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView_;

  @NonNull
  public final ViewPager2 gallerySlider;

  @NonNull
  public final GalleryPlaceholderBinding placeholderText;

  @NonNull
  public final RelativeLayout rootView;

  private GalleryBinding(@NonNull RelativeLayout rootView_, @NonNull ViewPager2 gallerySlider,
      @NonNull GalleryPlaceholderBinding placeholderText, @NonNull RelativeLayout rootView) {
    this.rootView_ = rootView_;
    this.gallerySlider = gallerySlider;
    this.placeholderText = placeholderText;
    this.rootView = rootView;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView_;
  }

  @NonNull
  public static GalleryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static GalleryBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.gallery, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static GalleryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.gallery_slider;
      ViewPager2 gallerySlider = ViewBindings.findChildViewById(rootView, id);
      if (gallerySlider == null) {
        break missingId;
      }

      id = R.id.placeholder_text;
      View placeholderText = ViewBindings.findChildViewById(rootView, id);
      if (placeholderText == null) {
        break missingId;
      }
      GalleryPlaceholderBinding binding_placeholderText = GalleryPlaceholderBinding.bind(placeholderText);

      RelativeLayout rootView_ = (RelativeLayout) rootView;

      return new GalleryBinding((RelativeLayout) rootView, gallerySlider, binding_placeholderText,
          rootView_);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
