// Generated by view binder compiler. Do not edit!
package app.grapheneos.camera.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AutoCompleteTextView;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.SwitchCompat;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import app.grapheneos.camera.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class MoreSettingsBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView_;

  @NonNull
  public final TextView cameraSoundsDescription;

  @NonNull
  public final ImageView cameraSoundsIcon;

  @NonNull
  public final LinearLayout cameraSoundsSetting;

  @NonNull
  public final SwitchCompat cameraSoundsSwitch;

  @NonNull
  public final TextView cameraSoundsTitle;

  @NonNull
  public final LinearLayout generalSettings;

  @NonNull
  public final LinearLayout gyroscopeSetting;

  @NonNull
  public final TextView gyroscopeSettingDescription;

  @NonNull
  public final ImageView gyroscopeSettingIcon;

  @NonNull
  public final SwitchCompat gyroscopeSettingSwitch;

  @NonNull
  public final TextView gyroscopeSettingTitle;

  @NonNull
  public final LinearLayout imageFormatSetting;

  @NonNull
  public final AutoCompleteTextView imageFormatSettingField;

  @NonNull
  public final ImageView imageFormatSettingIcon;

  @NonNull
  public final TextView imageFormatSettingTitle;

  @NonNull
  public final EditText photoQuality;

  @NonNull
  public final ImageView photoQualityIcon;

  @NonNull
  public final LinearLayout photoQualitySetting;

  @NonNull
  public final TextView photoQualitySubtitle;

  @NonNull
  public final TextView photoQualityTitle;

  @NonNull
  public final LinearLayout photoSettings;

  @NonNull
  public final ImageButton refreshStorageLocation;

  @NonNull
  public final ImageView removeExifIcon;

  @NonNull
  public final LinearLayout removeExifSetting;

  @NonNull
  public final TextView removeExifSubtitle;

  @NonNull
  public final TextView removeExifTitle;

  @NonNull
  public final SwitchCompat removeExifToggle;

  @NonNull
  public final LinearLayout rootView;

  @NonNull
  public final ImageView saveImageAsPreviewIcon;

  @NonNull
  public final LinearLayout saveImageAsPreviewSetting;

  @NonNull
  public final TextView saveImageAsPreviewSubtitle;

  @NonNull
  public final TextView saveImageAsPreviewTitle;

  @NonNull
  public final SwitchCompat saveImageAsPreviewToggle;

  @NonNull
  public final EditText storageLocationField;

  @NonNull
  public final ImageView storageLocationIcon;

  @NonNull
  public final LinearLayout storageLocationSetting;

  @NonNull
  public final LinearLayout storageLocationSettings;

  @NonNull
  public final TextView storageLocationTitle;

  @NonNull
  public final LinearLayout videoFormatSetting;

  @NonNull
  public final AutoCompleteTextView videoFormatSettingField;

  @NonNull
  public final ImageView videoFormatSettingIcon;

  @NonNull
  public final TextView videoFormatSettingTitle;

  @NonNull
  public final ImageView zslIcon;

  @NonNull
  public final LinearLayout zslSetting;

  @NonNull
  public final TextView zslSettingSubtitle;

  @NonNull
  public final TextView zslSettingTitle;

  @NonNull
  public final SwitchCompat zslSettingToggle;

  private MoreSettingsBinding(@NonNull ScrollView rootView_,
      @NonNull TextView cameraSoundsDescription, @NonNull ImageView cameraSoundsIcon,
      @NonNull LinearLayout cameraSoundsSetting, @NonNull SwitchCompat cameraSoundsSwitch,
      @NonNull TextView cameraSoundsTitle, @NonNull LinearLayout generalSettings,
      @NonNull LinearLayout gyroscopeSetting, @NonNull TextView gyroscopeSettingDescription,
      @NonNull ImageView gyroscopeSettingIcon, @NonNull SwitchCompat gyroscopeSettingSwitch,
      @NonNull TextView gyroscopeSettingTitle, @NonNull LinearLayout imageFormatSetting,
      @NonNull AutoCompleteTextView imageFormatSettingField,
      @NonNull ImageView imageFormatSettingIcon, @NonNull TextView imageFormatSettingTitle,
      @NonNull EditText photoQuality, @NonNull ImageView photoQualityIcon,
      @NonNull LinearLayout photoQualitySetting, @NonNull TextView photoQualitySubtitle,
      @NonNull TextView photoQualityTitle, @NonNull LinearLayout photoSettings,
      @NonNull ImageButton refreshStorageLocation, @NonNull ImageView removeExifIcon,
      @NonNull LinearLayout removeExifSetting, @NonNull TextView removeExifSubtitle,
      @NonNull TextView removeExifTitle, @NonNull SwitchCompat removeExifToggle,
      @NonNull LinearLayout rootView, @NonNull ImageView saveImageAsPreviewIcon,
      @NonNull LinearLayout saveImageAsPreviewSetting, @NonNull TextView saveImageAsPreviewSubtitle,
      @NonNull TextView saveImageAsPreviewTitle, @NonNull SwitchCompat saveImageAsPreviewToggle,
      @NonNull EditText storageLocationField, @NonNull ImageView storageLocationIcon,
      @NonNull LinearLayout storageLocationSetting, @NonNull LinearLayout storageLocationSettings,
      @NonNull TextView storageLocationTitle, @NonNull LinearLayout videoFormatSetting,
      @NonNull AutoCompleteTextView videoFormatSettingField,
      @NonNull ImageView videoFormatSettingIcon, @NonNull TextView videoFormatSettingTitle,
      @NonNull ImageView zslIcon, @NonNull LinearLayout zslSetting,
      @NonNull TextView zslSettingSubtitle, @NonNull TextView zslSettingTitle,
      @NonNull SwitchCompat zslSettingToggle) {
    this.rootView_ = rootView_;
    this.cameraSoundsDescription = cameraSoundsDescription;
    this.cameraSoundsIcon = cameraSoundsIcon;
    this.cameraSoundsSetting = cameraSoundsSetting;
    this.cameraSoundsSwitch = cameraSoundsSwitch;
    this.cameraSoundsTitle = cameraSoundsTitle;
    this.generalSettings = generalSettings;
    this.gyroscopeSetting = gyroscopeSetting;
    this.gyroscopeSettingDescription = gyroscopeSettingDescription;
    this.gyroscopeSettingIcon = gyroscopeSettingIcon;
    this.gyroscopeSettingSwitch = gyroscopeSettingSwitch;
    this.gyroscopeSettingTitle = gyroscopeSettingTitle;
    this.imageFormatSetting = imageFormatSetting;
    this.imageFormatSettingField = imageFormatSettingField;
    this.imageFormatSettingIcon = imageFormatSettingIcon;
    this.imageFormatSettingTitle = imageFormatSettingTitle;
    this.photoQuality = photoQuality;
    this.photoQualityIcon = photoQualityIcon;
    this.photoQualitySetting = photoQualitySetting;
    this.photoQualitySubtitle = photoQualitySubtitle;
    this.photoQualityTitle = photoQualityTitle;
    this.photoSettings = photoSettings;
    this.refreshStorageLocation = refreshStorageLocation;
    this.removeExifIcon = removeExifIcon;
    this.removeExifSetting = removeExifSetting;
    this.removeExifSubtitle = removeExifSubtitle;
    this.removeExifTitle = removeExifTitle;
    this.removeExifToggle = removeExifToggle;
    this.rootView = rootView;
    this.saveImageAsPreviewIcon = saveImageAsPreviewIcon;
    this.saveImageAsPreviewSetting = saveImageAsPreviewSetting;
    this.saveImageAsPreviewSubtitle = saveImageAsPreviewSubtitle;
    this.saveImageAsPreviewTitle = saveImageAsPreviewTitle;
    this.saveImageAsPreviewToggle = saveImageAsPreviewToggle;
    this.storageLocationField = storageLocationField;
    this.storageLocationIcon = storageLocationIcon;
    this.storageLocationSetting = storageLocationSetting;
    this.storageLocationSettings = storageLocationSettings;
    this.storageLocationTitle = storageLocationTitle;
    this.videoFormatSetting = videoFormatSetting;
    this.videoFormatSettingField = videoFormatSettingField;
    this.videoFormatSettingIcon = videoFormatSettingIcon;
    this.videoFormatSettingTitle = videoFormatSettingTitle;
    this.zslIcon = zslIcon;
    this.zslSetting = zslSetting;
    this.zslSettingSubtitle = zslSettingSubtitle;
    this.zslSettingTitle = zslSettingTitle;
    this.zslSettingToggle = zslSettingToggle;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView_;
  }

  @NonNull
  public static MoreSettingsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static MoreSettingsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.more_settings, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static MoreSettingsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.camera_sounds_description;
      TextView cameraSoundsDescription = ViewBindings.findChildViewById(rootView, id);
      if (cameraSoundsDescription == null) {
        break missingId;
      }

      id = R.id.camera_sounds_icon;
      ImageView cameraSoundsIcon = ViewBindings.findChildViewById(rootView, id);
      if (cameraSoundsIcon == null) {
        break missingId;
      }

      id = R.id.camera_sounds_setting;
      LinearLayout cameraSoundsSetting = ViewBindings.findChildViewById(rootView, id);
      if (cameraSoundsSetting == null) {
        break missingId;
      }

      id = R.id.camera_sounds_switch;
      SwitchCompat cameraSoundsSwitch = ViewBindings.findChildViewById(rootView, id);
      if (cameraSoundsSwitch == null) {
        break missingId;
      }

      id = R.id.camera_sounds_title;
      TextView cameraSoundsTitle = ViewBindings.findChildViewById(rootView, id);
      if (cameraSoundsTitle == null) {
        break missingId;
      }

      id = R.id.general_settings;
      LinearLayout generalSettings = ViewBindings.findChildViewById(rootView, id);
      if (generalSettings == null) {
        break missingId;
      }

      id = R.id.gyroscope_setting;
      LinearLayout gyroscopeSetting = ViewBindings.findChildViewById(rootView, id);
      if (gyroscopeSetting == null) {
        break missingId;
      }

      id = R.id.gyroscope_setting_description;
      TextView gyroscopeSettingDescription = ViewBindings.findChildViewById(rootView, id);
      if (gyroscopeSettingDescription == null) {
        break missingId;
      }

      id = R.id.gyroscope_setting_icon;
      ImageView gyroscopeSettingIcon = ViewBindings.findChildViewById(rootView, id);
      if (gyroscopeSettingIcon == null) {
        break missingId;
      }

      id = R.id.gyroscope_setting_switch;
      SwitchCompat gyroscopeSettingSwitch = ViewBindings.findChildViewById(rootView, id);
      if (gyroscopeSettingSwitch == null) {
        break missingId;
      }

      id = R.id.gyroscope_setting_title;
      TextView gyroscopeSettingTitle = ViewBindings.findChildViewById(rootView, id);
      if (gyroscopeSettingTitle == null) {
        break missingId;
      }

      id = R.id.image_format_setting;
      LinearLayout imageFormatSetting = ViewBindings.findChildViewById(rootView, id);
      if (imageFormatSetting == null) {
        break missingId;
      }

      id = R.id.image_format_setting_field;
      AutoCompleteTextView imageFormatSettingField = ViewBindings.findChildViewById(rootView, id);
      if (imageFormatSettingField == null) {
        break missingId;
      }

      id = R.id.image_format_setting_icon;
      ImageView imageFormatSettingIcon = ViewBindings.findChildViewById(rootView, id);
      if (imageFormatSettingIcon == null) {
        break missingId;
      }

      id = R.id.image_format_setting_title;
      TextView imageFormatSettingTitle = ViewBindings.findChildViewById(rootView, id);
      if (imageFormatSettingTitle == null) {
        break missingId;
      }

      id = R.id.photo_quality;
      EditText photoQuality = ViewBindings.findChildViewById(rootView, id);
      if (photoQuality == null) {
        break missingId;
      }

      id = R.id.photo_quality_icon;
      ImageView photoQualityIcon = ViewBindings.findChildViewById(rootView, id);
      if (photoQualityIcon == null) {
        break missingId;
      }

      id = R.id.photo_quality_setting;
      LinearLayout photoQualitySetting = ViewBindings.findChildViewById(rootView, id);
      if (photoQualitySetting == null) {
        break missingId;
      }

      id = R.id.photo_quality_subtitle;
      TextView photoQualitySubtitle = ViewBindings.findChildViewById(rootView, id);
      if (photoQualitySubtitle == null) {
        break missingId;
      }

      id = R.id.photo_quality_title;
      TextView photoQualityTitle = ViewBindings.findChildViewById(rootView, id);
      if (photoQualityTitle == null) {
        break missingId;
      }

      id = R.id.photo_settings;
      LinearLayout photoSettings = ViewBindings.findChildViewById(rootView, id);
      if (photoSettings == null) {
        break missingId;
      }

      id = R.id.refresh_storage_location;
      ImageButton refreshStorageLocation = ViewBindings.findChildViewById(rootView, id);
      if (refreshStorageLocation == null) {
        break missingId;
      }

      id = R.id.remove_exif_icon;
      ImageView removeExifIcon = ViewBindings.findChildViewById(rootView, id);
      if (removeExifIcon == null) {
        break missingId;
      }

      id = R.id.remove_exif_setting;
      LinearLayout removeExifSetting = ViewBindings.findChildViewById(rootView, id);
      if (removeExifSetting == null) {
        break missingId;
      }

      id = R.id.remove_exif_subtitle;
      TextView removeExifSubtitle = ViewBindings.findChildViewById(rootView, id);
      if (removeExifSubtitle == null) {
        break missingId;
      }

      id = R.id.remove_exif_title;
      TextView removeExifTitle = ViewBindings.findChildViewById(rootView, id);
      if (removeExifTitle == null) {
        break missingId;
      }

      id = R.id.remove_exif_toggle;
      SwitchCompat removeExifToggle = ViewBindings.findChildViewById(rootView, id);
      if (removeExifToggle == null) {
        break missingId;
      }

      id = R.id.root_view;
      LinearLayout rootView_ = ViewBindings.findChildViewById(rootView, id);
      if (rootView_ == null) {
        break missingId;
      }

      id = R.id.save_image_as_preview_icon;
      ImageView saveImageAsPreviewIcon = ViewBindings.findChildViewById(rootView, id);
      if (saveImageAsPreviewIcon == null) {
        break missingId;
      }

      id = R.id.save_image_as_preview_setting;
      LinearLayout saveImageAsPreviewSetting = ViewBindings.findChildViewById(rootView, id);
      if (saveImageAsPreviewSetting == null) {
        break missingId;
      }

      id = R.id.save_image_as_preview_subtitle;
      TextView saveImageAsPreviewSubtitle = ViewBindings.findChildViewById(rootView, id);
      if (saveImageAsPreviewSubtitle == null) {
        break missingId;
      }

      id = R.id.save_image_as_preview_title;
      TextView saveImageAsPreviewTitle = ViewBindings.findChildViewById(rootView, id);
      if (saveImageAsPreviewTitle == null) {
        break missingId;
      }

      id = R.id.save_image_as_preview_toggle;
      SwitchCompat saveImageAsPreviewToggle = ViewBindings.findChildViewById(rootView, id);
      if (saveImageAsPreviewToggle == null) {
        break missingId;
      }

      id = R.id.storage_location_field;
      EditText storageLocationField = ViewBindings.findChildViewById(rootView, id);
      if (storageLocationField == null) {
        break missingId;
      }

      id = R.id.storage_location_icon;
      ImageView storageLocationIcon = ViewBindings.findChildViewById(rootView, id);
      if (storageLocationIcon == null) {
        break missingId;
      }

      id = R.id.storage_location_setting;
      LinearLayout storageLocationSetting = ViewBindings.findChildViewById(rootView, id);
      if (storageLocationSetting == null) {
        break missingId;
      }

      id = R.id.storage_location_settings;
      LinearLayout storageLocationSettings = ViewBindings.findChildViewById(rootView, id);
      if (storageLocationSettings == null) {
        break missingId;
      }

      id = R.id.storage_location_title;
      TextView storageLocationTitle = ViewBindings.findChildViewById(rootView, id);
      if (storageLocationTitle == null) {
        break missingId;
      }

      id = R.id.video_format_setting;
      LinearLayout videoFormatSetting = ViewBindings.findChildViewById(rootView, id);
      if (videoFormatSetting == null) {
        break missingId;
      }

      id = R.id.video_format_setting_field;
      AutoCompleteTextView videoFormatSettingField = ViewBindings.findChildViewById(rootView, id);
      if (videoFormatSettingField == null) {
        break missingId;
      }

      id = R.id.video_format_setting_icon;
      ImageView videoFormatSettingIcon = ViewBindings.findChildViewById(rootView, id);
      if (videoFormatSettingIcon == null) {
        break missingId;
      }

      id = R.id.video_format_setting_title;
      TextView videoFormatSettingTitle = ViewBindings.findChildViewById(rootView, id);
      if (videoFormatSettingTitle == null) {
        break missingId;
      }

      id = R.id.zsl_icon;
      ImageView zslIcon = ViewBindings.findChildViewById(rootView, id);
      if (zslIcon == null) {
        break missingId;
      }

      id = R.id.zsl_setting;
      LinearLayout zslSetting = ViewBindings.findChildViewById(rootView, id);
      if (zslSetting == null) {
        break missingId;
      }

      id = R.id.zsl_setting_subtitle;
      TextView zslSettingSubtitle = ViewBindings.findChildViewById(rootView, id);
      if (zslSettingSubtitle == null) {
        break missingId;
      }

      id = R.id.zsl_setting_title;
      TextView zslSettingTitle = ViewBindings.findChildViewById(rootView, id);
      if (zslSettingTitle == null) {
        break missingId;
      }

      id = R.id.zsl_setting_toggle;
      SwitchCompat zslSettingToggle = ViewBindings.findChildViewById(rootView, id);
      if (zslSettingToggle == null) {
        break missingId;
      }

      return new MoreSettingsBinding((ScrollView) rootView, cameraSoundsDescription,
          cameraSoundsIcon, cameraSoundsSetting, cameraSoundsSwitch, cameraSoundsTitle,
          generalSettings, gyroscopeSetting, gyroscopeSettingDescription, gyroscopeSettingIcon,
          gyroscopeSettingSwitch, gyroscopeSettingTitle, imageFormatSetting,
          imageFormatSettingField, imageFormatSettingIcon, imageFormatSettingTitle, photoQuality,
          photoQualityIcon, photoQualitySetting, photoQualitySubtitle, photoQualityTitle,
          photoSettings, refreshStorageLocation, removeExifIcon, removeExifSetting,
          removeExifSubtitle, removeExifTitle, removeExifToggle, rootView_, saveImageAsPreviewIcon,
          saveImageAsPreviewSetting, saveImageAsPreviewSubtitle, saveImageAsPreviewTitle,
          saveImageAsPreviewToggle, storageLocationField, storageLocationIcon,
          storageLocationSetting, storageLocationSettings, storageLocationTitle, videoFormatSetting,
          videoFormatSettingField, videoFormatSettingIcon, videoFormatSettingTitle, zslIcon,
          zslSetting, zslSettingSubtitle, zslSettingTitle, zslSettingToggle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
